title: Learning Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: learning deadlines
author: Abhishek Das

domain: "https://stephenhzs.github.io/stephenHzs1.github.io/ "
baseurl: ""

twitter_username: abhshkdz
twitter_hashtag: machinelearning
github_username: stephenHzs
github_repo: stephenHzs1.github.io

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']